
CMD := test ls echo mkdir rmdir cp mv ln sleep rm cat expr \
       basename dirname kill true false chmod whoami more du \
       dd date uname pwd env printenv which chsh tty grep mknod \
       nice cmp

include cmd.mk
