#!/bin/sh
#
# Copyright (c) 2017, Piotr Durlej
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

set -e

. s/env.sh

: ${ARCH:=amd64}

gmake symlinks
gmake clean
gmake

rm -rf	 release
mkdir -p release/release/pxe/tftpboot/m
mkdir -p release/release/cdrom
mkdir -p release/release/usb

cp -p	disks/cdrom.iso		release/release/cdrom/cdrom.iso
cp -p	disks/altcd.iso		release/release/cdrom/altcd.iso
cp -p	disks/hdflat.img	release/release/usb/usb.img
cp -p	sysload/sysload.pxe	release/release/pxe/tftpboot/m/sysload
cp -p	disks/pxe.img		release/release/pxe/tftpboot/m/image
cp -p	doc/pxe.example		release/release/pxe/dhcpd.conf.example

sysver=$(cross/sysver)

(cd release && tar cf ../release-$sysver-$ARCH.tar release)
rm -f release-$sysver-$ARCH.tar.gz
gzip release-$sysver-$ARCH.tar
