#
# Copyright (c) 2017, Piotr Durlej
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

include config.mk

all:
	cd filemgr	&& $(MAKE) all
	cd sh		&& $(MAKE) all
	cd bin		&& $(MAKE) all
	cd sbin		&& $(MAKE) all
	cd tests	&& $(MAKE) all
	cd tcc		&& $(MAKE) all
	cd tcc.lib	&& $(MAKE) all
	cd acex-bin	&& $(MAKE) all
	cd acex-sbin	&& $(MAKE) all
	cd sdk.bin	&& $(MAKE) all
	cd umake	&& $(MAKE) all

clean:
	cd filemgr	&& $(MAKE) clean
	cd sh		&& $(MAKE) clean
	cd bin		&& $(MAKE) clean
	cd sbin		&& $(MAKE) clean
	cd tests	&& $(MAKE) clean
	cd tcc		&& $(MAKE) clean
	cd tcc.lib	&& $(MAKE) clean
	cd acex-bin	&& $(MAKE) clean
	cd acex-sbin	&& $(MAKE) clean
	cd sdk.bin	&& $(MAKE) clean
	cd umake	&& $(MAKE) clean
