
include config.mk

all:
	cd filemgr	&& $(MAKE) all
	cd sh		&& $(MAKE) all
	cd bin		&& $(MAKE) all
	cd sbin		&& $(MAKE) all
	cd tests	&& $(MAKE) all
	cd acex-bin	&& $(MAKE) all
	cd acex-sbin	&& $(MAKE) all

clean:
	cd filemgr	&& $(MAKE) clean
	cd sh		&& $(MAKE) clean
	cd bin		&& $(MAKE) clean
	cd sbin		&& $(MAKE) clean
	cd tests	&& $(MAKE) clean
	cd acex-bin	&& $(MAKE) clean
	cd acex-sbin	&& $(MAKE) clean
