
CMD := test.alarm test.color test.gui test.memdev test.pipe test.printf	\
       test.pty test.vtty test.timer test.time				\
       test.getopt test.regexp test.segv				\
       test.ringbuf test.textsize test.sleep test.fmthuman		\
       test.strftime test.hideptr

include cmd.mk
